const globalObject = {
    name: "Турция",
    brockersReels: [
      {
        id: 1,
        name: "Алина",
        avatar: true,
        viewedStor: true,
        imgReels: process.env.PUBLIC_URL + "/images/stor1.jpeg",
      },
      {
        id: 2,
        name: "Ксения",
        avatar: true,
        viewedStor: true,
        imgReels: process.env.PUBLIC_URL + "/images/stor2.jpg",
      },
      {
        id: 3,
        name: "Евгений",
        avatar: true,
        viewedStor: true,
        imgReels: process.env.PUBLIC_URL + "/images/stor3.jpg",
      },
      {
        id: 4,
        name: "Татьяна",
        avatar: true,
        viewedStor: false,
        imgReels: process.env.PUBLIC_URL + "/images/stor4.jpeg",
      },
      {
        id: 5,
        name: "Алина",
        avatar: true,
        viewedStor: false,
        imgReels: process.env.PUBLIC_URL + "/images/stor5.jpg",
      },
      {
        id: 6,
        name: "Алина",
        avatar: true,
        viewedStor: true,
        imgReels: process.env.PUBLIC_URL + "/images/stor6.jpg",
      },
      {
        id: 7,
        name: "Алина",
        avatar: true,
        viewedStor: true,
        imgReels: process.env.PUBLIC_URL + "/images/stor7.jpg",
      },
      {
        id: 8,
        name: "Алина",
        avatar: true,
        viewedStor: true,
        imgReels: process.env.PUBLIC_URL + "/images/stor1.jpeg",
      },
      {
        id: 9,
        name: "Алина",
        avatar: true,
        viewedStor: true,
        imgReels: process.env.PUBLIC_URL + "/images/stor2.jpg",
      },
      {
        id: 10,
        name: "Алина",
        avatar: true,
        viewedStor: true,
        imgReels: process.env.PUBLIC_URL + "/images/stor3.jpg",
      },
    ],
    aparts: [
      {
        id: 1,
        locationName: "Северный Кипр",
        name: "Wings Tower",
        brocker: "Татьяна",
        brockerAvatar: process.env.PUBLIC_URL + "/images/brocker_avatar3.jpg",
        price: 40000,
        status: "Продажа",
        likeCounter: 52,
        locations: [
          { lat: 36.887730, lng: 30.703146, name: "Вы" },
          { lat: 36.887561, lng: 30.704884, name: "Wings Tower" },
        ],
        url: [
          process.env.PUBLIC_URL + "/images/aparts1.png",
          process.env.PUBLIC_URL + "/images/aparts2.png",
          process.env.PUBLIC_URL + "/images/aparts3.png",
          process.env.PUBLIC_URL + "/images/aparts4.png",
          process.env.PUBLIC_URL + "/images/aparts5.png",
        ],
        description: "Momentum Phuket — это смешанное сообщество, расположенное недалеко от пляжа Банг Тао. Он предлагает разнообразные возможности для отдыха и проживания, сочетая современные удобства с природной красотой острова. В сообществе есть жилые комплексы, виллы и апартаменты, подходящие как для краткосрочного, так и для долгосрочного проживания. Жители и гости Momentum Phuket могут насладиться широким спектром услуг и развлечений, включая рестораны, кафе, магазины, фитнес-центры и спа-салоны. Для любителей активного отдыха предусмотрены бассейны, теннисные корты и зоны для занятия водными видами спорта. На территории также есть парковые зоны и пешеходные маршруты, позволяющие насладиться тропической природой.",
        infrastructure: ["Баня","Хамам","SPA","Бассейн","Дома","Школа","Магазин"],
      },
      {
        id: 2,
        locationName: "Алания",
        name: "Wings Tower",
        brocker: "Алина",
        brockerAvatar: process.env.PUBLIC_URL + "/images/brocker_avatar2.jpg",
        price: 30000,
        status: "Продажа",
        likeCounter: 32,
        locations: [
          { lat: 36.887730, lng: 30.703146, name: "Вы" },
          { lat: 36.887561, lng: 30.704884, name: "Wings Tower" },
        ],
        url: [
          process.env.PUBLIC_URL + "/images/aparts6.png",
          process.env.PUBLIC_URL + "/images/aparts7.png",
          process.env.PUBLIC_URL + "/images/aparts8.png",
          process.env.PUBLIC_URL + "/images/aparts9.png",
          process.env.PUBLIC_URL + "/images/aparts10.png",
        ],
        description: "Momentum Phuket — это смешанное сообщество, расположенное недалеко от пляжа Банг Тао. Он предлагает разнообразные возможности для отдыха и проживания, сочетая современные удобства с природной красотой острова. В сообществе есть жилые комплексы, виллы и апартаменты, подходящие как для краткосрочного, так и для долгосрочного проживания. Жители и гости Momentum Phuket могут насладиться широким спектром услуг и развлечений, включая рестораны, кафе, магазины, фитнес-центры и спа-салоны. Для любителей активного отдыха предусмотрены бассейны, теннисные корты и зоны для занятия водными видами спорта. На территории также есть парковые зоны и пешеходные маршруты, позволяющие насладиться тропической природой.",
        infrastructure: ["Баня","Хамам","SPA","Бассейн","Дома","Школа","Магазин"],
      },
      {
        id: 3,
        locationName: "Анталия",
        name: "Wings Tower",
        brocker: "Светлана",
        brockerAvatar: process.env.PUBLIC_URL + "/images/brocker_avatar1.jpg",
        price: 50000,
        status: "Продажа",
        likeCounter: 22,
        locations: [
          { lat: 36.887730, lng: 30.703146, name: "Вы" },
          { lat: 36.887561, lng: 30.704884, name: "Wings Tower" },
        ],
        url: [
          process.env.PUBLIC_URL + "/images/aparts11.png",
          process.env.PUBLIC_URL + "/images/aparts12.png",
          process.env.PUBLIC_URL + "/images/aparts13.png",
          process.env.PUBLIC_URL + "/images/aparts14.png",
          process.env.PUBLIC_URL + "/images/aparts1.png",
        ],
        description: "Momentum Phuket — это смешанное сообщество, расположенное недалеко от пляжа Банг Тао. Он предлагает разнообразные возможности для отдыха и проживания, сочетая современные удобства с природной красотой острова. В сообществе есть жилые комплексы, виллы и апартаменты, подходящие как для краткосрочного, так и для долгосрочного проживания. Жители и гости Momentum Phuket могут насладиться широким спектром услуг и развлечений, включая рестораны, кафе, магазины, фитнес-центры и спа-салоны. Для любителей активного отдыха предусмотрены бассейны, теннисные корты и зоны для занятия водными видами спорта. На территории также есть парковые зоны и пешеходные маршруты, позволяющие насладиться тропической природой.",
        infrastructure: ["Баня","Хамам","SPA","Бассейн","Дома","Школа","Магазин"],
      },
    ],
  };

  export default globalObject;